version: '3'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:80"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./auth-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3001:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: ${DSN}

  postgres:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres:
