version: '3'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:80"
    deploy:
      mode: replicated
      replicas: 1

volumes:
  postgres:
